// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: internal/server/turbo.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{1}
}

type NotifyDirectioresBuiltRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory []string `protobuf:"bytes,1,rep,name=directory,proto3" json:"directory,omitempty"`
	Hash      string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *NotifyDirectioresBuiltRequest) Reset() {
	*x = NotifyDirectioresBuiltRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDirectioresBuiltRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDirectioresBuiltRequest) ProtoMessage() {}

func (x *NotifyDirectioresBuiltRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDirectioresBuiltRequest.ProtoReflect.Descriptor instead.
func (*NotifyDirectioresBuiltRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{2}
}

func (x *NotifyDirectioresBuiltRequest) GetDirectory() []string {
	if x != nil {
		return x.Directory
	}
	return nil
}

func (x *NotifyDirectioresBuiltRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type NotifyDirectoriesBuiltReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NotifyDirectoriesBuiltReply) Reset() {
	*x = NotifyDirectoriesBuiltReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyDirectoriesBuiltReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyDirectoriesBuiltReply) ProtoMessage() {}

func (x *NotifyDirectoriesBuiltReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyDirectoriesBuiltReply.ProtoReflect.Descriptor instead.
func (*NotifyDirectoriesBuiltReply) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{3}
}

type ShouldRestoreDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Directory string `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"`
	Hash      string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *ShouldRestoreDirectoryRequest) Reset() {
	*x = ShouldRestoreDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldRestoreDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldRestoreDirectoryRequest) ProtoMessage() {}

func (x *ShouldRestoreDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldRestoreDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ShouldRestoreDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{4}
}

func (x *ShouldRestoreDirectoryRequest) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *ShouldRestoreDirectoryRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ShouldRestoreDirectoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OkToRestore []string `protobuf:"bytes,1,rep,name=okToRestore,proto3" json:"okToRestore,omitempty"`
}

func (x *ShouldRestoreDirectoryReply) Reset() {
	*x = ShouldRestoreDirectoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_server_turbo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShouldRestoreDirectoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldRestoreDirectoryReply) ProtoMessage() {}

func (x *ShouldRestoreDirectoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_turbo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldRestoreDirectoryReply.ProtoReflect.Descriptor instead.
func (*ShouldRestoreDirectoryReply) Descriptor() ([]byte, []int) {
	return file_internal_server_turbo_proto_rawDescGZIP(), []int{5}
}

func (x *ShouldRestoreDirectoryReply) GetOkToRestore() []string {
	if x != nil {
		return x.OkToRestore
	}
	return nil
}

var File_internal_server_turbo_proto protoreflect.FileDescriptor

var file_internal_server_turbo_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x51, 0x0a, 0x1d, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x1d, 0x0a, 0x1b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x51, 0x0a, 0x1d, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x3f, 0x0a, 0x1b, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x6b, 0x54, 0x6f, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x6b, 0x54, 0x6f,
	0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x32, 0x89, 0x02, 0x0a, 0x05, 0x54, 0x75, 0x72, 0x62,
	0x6f, 0x12, 0x30, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x16, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x12, 0x25, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x72, 0x65, 0x73, 0x42, 0x75, 0x69, 0x6c, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x42,
	0x75, 0x69, 0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x16, 0x53,
	0x68, 0x6f, 0x75, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53,
	0x68, 0x6f, 0x75, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x68, 0x6f, 0x75, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x76, 0x65, 0x72, 0x63, 0x65, 0x6c, 0x2f, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x72, 0x65,
	0x70, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_server_turbo_proto_rawDescOnce sync.Once
	file_internal_server_turbo_proto_rawDescData = file_internal_server_turbo_proto_rawDesc
)

func file_internal_server_turbo_proto_rawDescGZIP() []byte {
	file_internal_server_turbo_proto_rawDescOnce.Do(func() {
		file_internal_server_turbo_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_server_turbo_proto_rawDescData)
	})
	return file_internal_server_turbo_proto_rawDescData
}

var file_internal_server_turbo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_server_turbo_proto_goTypes = []interface{}{
	(*PingRequest)(nil),                   // 0: server.PingRequest
	(*PingReply)(nil),                     // 1: server.PingReply
	(*NotifyDirectioresBuiltRequest)(nil), // 2: server.NotifyDirectioresBuiltRequest
	(*NotifyDirectoriesBuiltReply)(nil),   // 3: server.NotifyDirectoriesBuiltReply
	(*ShouldRestoreDirectoryRequest)(nil), // 4: server.ShouldRestoreDirectoryRequest
	(*ShouldRestoreDirectoryReply)(nil),   // 5: server.ShouldRestoreDirectoryReply
}
var file_internal_server_turbo_proto_depIdxs = []int32{
	0, // 0: server.Turbo.Ping:input_type -> server.PingRequest
	2, // 1: server.Turbo.NotifyDirectoriesBuilt:input_type -> server.NotifyDirectioresBuiltRequest
	4, // 2: server.Turbo.ShouldRestoreDirectory:input_type -> server.ShouldRestoreDirectoryRequest
	1, // 3: server.Turbo.Ping:output_type -> server.PingReply
	3, // 4: server.Turbo.NotifyDirectoriesBuilt:output_type -> server.NotifyDirectoriesBuiltReply
	5, // 5: server.Turbo.ShouldRestoreDirectory:output_type -> server.ShouldRestoreDirectoryReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_server_turbo_proto_init() }
func file_internal_server_turbo_proto_init() {
	if File_internal_server_turbo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_server_turbo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_turbo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_turbo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyDirectioresBuiltRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_turbo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyDirectoriesBuiltReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_turbo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldRestoreDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_server_turbo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShouldRestoreDirectoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_server_turbo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_turbo_proto_goTypes,
		DependencyIndexes: file_internal_server_turbo_proto_depIdxs,
		MessageInfos:      file_internal_server_turbo_proto_msgTypes,
	}.Build()
	File_internal_server_turbo_proto = out.File
	file_internal_server_turbo_proto_rawDesc = nil
	file_internal_server_turbo_proto_goTypes = nil
	file_internal_server_turbo_proto_depIdxs = nil
}
