// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: internal/server/turbo.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TurboClient is the client API for Turbo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TurboClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	// Implement cache watching
	NotifyDirectoriesBuilt(ctx context.Context, in *NotifyDirectioresBuiltRequest, opts ...grpc.CallOption) (*NotifyDirectoriesBuiltReply, error)
	ShouldRestoreDirectory(ctx context.Context, in *ShouldRestoreDirectoryRequest, opts ...grpc.CallOption) (*ShouldRestoreDirectoryReply, error)
}

type turboClient struct {
	cc grpc.ClientConnInterface
}

func NewTurboClient(cc grpc.ClientConnInterface) TurboClient {
	return &turboClient{cc}
}

func (c *turboClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/server.Turbo/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboClient) NotifyDirectoriesBuilt(ctx context.Context, in *NotifyDirectioresBuiltRequest, opts ...grpc.CallOption) (*NotifyDirectoriesBuiltReply, error) {
	out := new(NotifyDirectoriesBuiltReply)
	err := c.cc.Invoke(ctx, "/server.Turbo/NotifyDirectoriesBuilt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turboClient) ShouldRestoreDirectory(ctx context.Context, in *ShouldRestoreDirectoryRequest, opts ...grpc.CallOption) (*ShouldRestoreDirectoryReply, error) {
	out := new(ShouldRestoreDirectoryReply)
	err := c.cc.Invoke(ctx, "/server.Turbo/ShouldRestoreDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurboServer is the server API for Turbo service.
// All implementations must embed UnimplementedTurboServer
// for forward compatibility
type TurboServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	// Implement cache watching
	NotifyDirectoriesBuilt(context.Context, *NotifyDirectioresBuiltRequest) (*NotifyDirectoriesBuiltReply, error)
	ShouldRestoreDirectory(context.Context, *ShouldRestoreDirectoryRequest) (*ShouldRestoreDirectoryReply, error)
	mustEmbedUnimplementedTurboServer()
}

// UnimplementedTurboServer must be embedded to have forward compatible implementations.
type UnimplementedTurboServer struct {
}

func (UnimplementedTurboServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTurboServer) NotifyDirectoriesBuilt(context.Context, *NotifyDirectioresBuiltRequest) (*NotifyDirectoriesBuiltReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyDirectoriesBuilt not implemented")
}
func (UnimplementedTurboServer) ShouldRestoreDirectory(context.Context, *ShouldRestoreDirectoryRequest) (*ShouldRestoreDirectoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShouldRestoreDirectory not implemented")
}
func (UnimplementedTurboServer) mustEmbedUnimplementedTurboServer() {}

// UnsafeTurboServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurboServer will
// result in compilation errors.
type UnsafeTurboServer interface {
	mustEmbedUnimplementedTurboServer()
}

func RegisterTurboServer(s grpc.ServiceRegistrar, srv TurboServer) {
	s.RegisterService(&Turbo_ServiceDesc, srv)
}

func _Turbo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Turbo/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turbo_NotifyDirectoriesBuilt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyDirectioresBuiltRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboServer).NotifyDirectoriesBuilt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Turbo/NotifyDirectoriesBuilt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboServer).NotifyDirectoriesBuilt(ctx, req.(*NotifyDirectioresBuiltRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Turbo_ShouldRestoreDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShouldRestoreDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurboServer).ShouldRestoreDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Turbo/ShouldRestoreDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurboServer).ShouldRestoreDirectory(ctx, req.(*ShouldRestoreDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Turbo_ServiceDesc is the grpc.ServiceDesc for Turbo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Turbo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.Turbo",
	HandlerType: (*TurboServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Turbo_Ping_Handler,
		},
		{
			MethodName: "NotifyDirectoriesBuilt",
			Handler:    _Turbo_NotifyDirectoriesBuilt_Handler,
		},
		{
			MethodName: "ShouldRestoreDirectory",
			Handler:    _Turbo_ShouldRestoreDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/server/turbo.proto",
}
